### ISSUE TITLE
More clarity on cards component

### ISSUE THREAD

**Issue by Avuidrauxs** [GroceriStar/cards-wrapper-component#1]
#### More to come...

**Comment by atherdon** [comment]
i think we should start with simple things. did you review this small package and understand everything? i think it's self explanatory.
if it's clear for you - then move cards here at components. connect them and return at index.js

**Comment by atherdon** [comment]
i assume we need to install here:  https://github.com/GroceriStar/grocery-react-component, because we have a List component there, that can be handy for us.

we don't need to have a `fetch` plugin here, because we'll send all import data from Parent components

list of components that should be moved here:
- [ ]  Cards.js
- [ ]  Card1.js
- [ ]  Card2.js
- [ ]  Card3.js
- [ ]  Card4.js
- [ ]  Card5.js
and index.js from that folder can be useful here(but with updates...)

**Comment by atherdon** [comment]
feel free and tell me if you need more details on this task. i'm actually working with recipe-antd project, so can help you quickly. I also can make a short video - tell me if it necessary

**Comment by Avuidrauxs** [comment]
@atherdon , Oh yes I would very much love a video. 😄

**Comment by atherdon** [comment]
i'm glad that it can help. will create a few videos, related to our component modules and share with you when i wake up. if you have time for quick task, i buzz you at this comment https://github.com/GroceriStar/groceristar-fetch/issues/185#issuecomment-460056430

**Comment by atherdon** [comment]
it takes more time that i assume, sorry for this.
check this link - tell me if it wouldn't work
https://drive.google.com/file/d/1V0OlopnsOw26FUdWZj_wIBLumQUiXbCL/view

**Comment by atherdon** [comment]
ok, closing it
